# -*- coding: utf-8 -*-
"""Impact of New Playlist Recommendation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yCK9ujC9qq6Sbw-p_P5Ti1MfeqZy3teG

# A/B Testing
> A/B testing is a method used to compare two versions of a product, page, or application to determine which one performs better. This document provides an overview of how to conduct A/B testing.

# Project's Aim
"This analysis aims to evaluate the impact of the new playlist recommendation algorithm on user engagement within Spotify. The data includes two groups: a 'Control' group, representing users who did not receive the new algorithm, and a 'Variant' group, representing users who did. The primary metric for user engagement is the 'Duration Played' column.

#Datasets:

Site A/B test data: https://docs.google.com/spreadsheets/d/e/2PACX-1vTQeu7yHoA0tdMZbxzaYcY_F_5oL-4GwFYgo5p2PtycUbYOmD7YFajiFWzXaQxf1w/pub?gid=2014393006&single=true&output=csv
"""

import pandas as pd
import seaborn as sns
from scipy.stats import shapiro, mannwhitneyu, ttest_ind
import matplotlib.pyplot as plt
from scipy.stats import shapiro, mannwhitneyu, ttest_ind, levene

"""# 1. Load the Data

First, we loaded and explored the data to understand its basic structure and the distribution of users across the two groups. Descriptive statistics were calculated for the 'Duration Played' metric within each group to get an initial sense of the central tendency and spread.
"""

#https://docs.google.com/spreadsheets/d/e/2PACX-1vTQeu7yHoA0tdMZbxzaYcY_F_5oL-4GwFYgo5p2PtycUbYOmD7YFajiFWzXaQxf1w/pub?gid=2014393006&single=true&output=csv
google_sheets_link = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTQeu7yHoA0tdMZbxzaYcY_F_5oL-4GwFYgo5p2PtycUbYOmD7YFajiFWzXaQxf1w/pub?gid=2014393006&single=true&output=csv'
df_spotify = pd.read_csv(google_sheets_link, sep=',')

df_spotify.head()

"""# 2. Initial Data Exploration"""

print(df_spotify['Group'].value_counts())

df_spotify.info()

df_spotify.drop_duplicates(inplace=True)

"""# 3. Descriptive Analysis of 'Engagement' by Group"""

sns.countplot(data=df_spotify, x='Group')
plt.title('Data Distribution per Group')
plt.xlabel('Group')
plt.ylabel('Number of Users')
plt.show()

# Descriptive Analysis of 'Engagement' by Group
print("\nDescriptive Statistics of 'Duration Played' per Group:")
grouped_duration = df_spotify.groupby('Group')['Duration Played']
print(grouped_duration.describe().T)

sns.barplot(data=df_spotify, x='Group', y='Duration Played')
plt.title('Average Duration Played per Group')
plt.xlabel('Group')
plt.ylabel('Average Duration Played (e.g., in seconds)')
plt.show()

"""# 4. Normality Test (Shapiro-Wilk) for 'Engagement' per Group

To determine the appropriate statistical test for comparing the 'Duration Played' between the two groups, we conducted a Shapiro-Wilk test to assess the normality of the 'Duration Played' data within each group. The results of the Shapiro-Wilk test indicated whether the assumption of normality was met for either or both groups.
"""

print("\n--- Shapiro-Wilk Normality Test for Duration Played ---")
alpha = 0.05 # Significance level

for group in df_spotify["Group"].unique():
    duration_data = df_spotify.loc[df_spotify['Group'] == group, "Duration Played"]
    statistic, p_value = shapiro(duration_data)
    print(f"Group: {group} \nStatistic: {statistic:.3f}\nP-Value: {p_value:.3f}\n")
    if p_value < alpha:
        print(f"Conclusion for Group {group}: The p-value ({p_value:.3f}) is less than {alpha}, so we reject the null hypothesis. The 'Duration Played' data for this group does not follow a normal distribution.\n")
    else:
        print(f"Conclusion for Group {group}: The p-value ({p_value:.3f}) is greater than or equal to {alpha}, so we fail to reject the null hypothesis. The 'Duration Played' data for this group may follow a normal distribution.\n")

"""Hypothesis 1 - Shapiro (Normality):
H₀: The 'Duration Played' data for each group follows a normal distribution.
H₁: The 'Duration Played' data for at least one group does not follow a normal distribution.

The Shapiro-Wilk tests suggested that the 'Duration Played' data for both the Control (p = 0.978) and Target (p = 0.834) groups may follow a normal distribution, as we failed to reject the null hypothesis for both.

# 5. Homogeneity of Variances Test (Levene's Test) - Conduct if normality is assumed for both groups
"""

normality_assumed_duration = all(shapiro(df_spotify.loc[df_spotify['Group'] == group, "Duration Played"])[1] >= alpha for group in df_spotify["Group"].unique())

if normality_assumed_duration:
    print("\n--- Levene's Test for Homogeneity of Variances (Duration Played) ---")
    control_duration = df_spotify.loc[df_spotify['Group'] == 'Control', 'Duration Played']
    target_duration = df_spotify.loc[df_spotify['Group'] == 'Target', 'Duration Played']
    statistic_levene_duration, p_value_levene_duration = levene(control_duration, target_duration)
    print(f"Levene Statistic: {statistic_levene_duration:.3f}")
    print(f"P-Value (Levene): {p_value_levene_duration:.3f}")
    if p_value_levene > alpha:
        print("Conclusion: The p-value is greater than the significance level, so we fail to reject the null hypothesis. The variances of 'Duration Played' between the two groups are assumed to be homogeneous.\n")
        homogenous_variance = True
    else:
        print("Conclusion: The p-value is less than the significance level, so we reject the null hypothesis. The variances of 'Duration Played' between the two groups are not assumed to be homogeneous.\n")
        homogenous_variance = False
else:
    print("\nNormality assumption not met for at least one group. Skipping Levene's test.")
    homogenous_variance = False

"""# 6. Hypothesis Testing

Based on the results of the normality and homogeneity of variances tests, we selected the appropriate hypothesis test:
* If the normality assumption was not met for at least one group, we used the non-parametric Mann-Whitney U test to compare the distributions of 'Duration Played' between the two groups.
* If the normality assumption was met for both groups and the variances were assumed to be homogeneous, we used the independent t-test to compare the mean 'Engagement' between the two groups.
* If the normality assumption was met for both groups but the variances were not assumed to be homogeneous, we used Welch's t-test (an adaptation of the t-test for unequal variances).

The p-value from the chosen hypothesis test was then used to determine whether there was a statistically significant difference in 'Duration Played' between the Variant and Control groups at a significance level of 0.05.
"""

print("\n--- Hypothesis Testing for 'Duration Played' ---")

"""## Welch's t-test."""

# Since the Shapiro-Wilk test suggests that 'Duration Played' data for both groups may follow a normal distribution, but Levene's test indicates that the variances are NOT homogeneous, we will use Welch's t-test.

print("\nUsing parametric Welch's t-test because normality is assumed, but variances are not homogeneous.")
statistic_welch_duration, p_value_welch_duration = ttest_ind(target_duration, control_duration, equal_var=False)
print(f"Welch's t-test Statistic: {statistic_welch_duration:.3f}")
print(f"P-Value (Welch's t-test): {p_value_welch_duration:.3f}")

"""Hypothesis 2 - Equality (Mean Duration Played):
H₀: µ₁ = µ₂ (There is no statistical difference in the mean 'Duration Played' between the Control and Target groups).
H₁: µ₁ ≠ µ₂ (There is a statistical difference in the mean 'Duration Played' between the Control and Target groups).

The Welch's t-test, conducted due to unequal variances (Levene's p = 0.932, rejecting homogeneity), yielded a statistically significant p-value of 0.000. Therefore, we reject the null hypothesis. There is a statistically significant difference in the mean 'Duration Played' between the Target and Control groups. The Target group exhibited a significantly higher mean 'Duration Played' (159.91 seconds) compared to the Control group (120.07 seconds), indicating a positive impact of the new playlist recommendation algorithm on user listening time.
"""

if p_value_welch_duration < alpha:
    print(f"Conclusion: The p-value ({p_value_welch_duration:.3f}) is less than {alpha}, so we reject the null hypothesis.")
    print("There is a statistically significant difference in the mean 'Duration Played' between the Target and Control groups (with unequal variances).\n")
else:
    print(f"Conclusion: The p-value ({p_value_welch_duration:.3f}) is greater than or equal to {alpha}, so we fail to reject the null hypothesis.")
    print("There is no statistically significant difference in the mean 'Duration Played' between the Target and Control groups (with unequal variances).\n")

print("\n--- Interpretation of Results for 'Duration Played' ---")
print("\nMean 'Duration Played' per Group:")
print(df_spotify.groupby('Group')['Duration Played'].mean())
print("\nMedian 'Duration Played' per Group:")
print(df_spotify.groupby('Group')['Duration Played'].median())

print("\nBased on the statistical test performed:")
print("Welch's t-test compared the mean 'Duration Played' between the Target (new algorithm) and Control groups, accounting for unequal variances.")
if p_value_welch_duration < alpha:
    print("The statistically significant p-value suggests that the new playlist recommendation algorithm has a significant impact on the average duration users play music.")
    mean_control_duration = df_spotify.loc[df_spotify['Group'] == 'Control', 'Duration Played'].mean()
    mean_target_duration = df_spotify.loc[df_spotify['Group'] == 'Target', 'Duration Played'].mean()
    if mean_target_duration > mean_control_duration:
        print(f"The mean 'Duration Played' in the Target group ({mean_target_duration:.2f}) is higher than in the Control group ({mean_control_duration:.2f}), indicating a potential positive impact on listening time.")
    elif mean_target_duration < mean_control_duration:
        print(f"The mean 'Duration Played' in the Target group ({mean_target_duration:.2f}) is lower than in the Control group ({mean_control_duration:.2f}), indicating a potential negative impact on listening time.")
    else:
        print("The mean 'Duration Played' is similar between the two groups.")
else:
    print("The non-significant p-value suggests that there is no statistically significant difference in the average duration users play music between the two groups, even when accounting for unequal variances.")

"""# 7. Interpretation of Results"""

print("\n--- Interpretation of Results for 'Duration Played' ---")

print("\nMean 'Duration Played' per Group:")
print(df_spotify.groupby('Group')['Duration Played'].mean())

print("\nMedian 'Duration Played' per Group:")
print(df_spotify.groupby('Group')['Duration Played'].median())

print("\nBased on the statistical test performed:")
print("Welch's t-test compared the mean 'Duration Played' between the Target (new algorithm) and Control groups, accounting for unequal variances.")
print("The statistically significant p-value (0.000, which is less than 0.05) indicates that we reject the null hypothesis.")
print("This suggests there is a statistically significant difference in the average duration users play music between the two groups.")
print(f"The mean 'Duration Played' in the Target group (159.91 seconds) is significantly higher than in the Control group (120.07 seconds).")
print("This provides evidence that the new playlist recommendation algorithm has a positive impact on listening time, as users exposed to the new algorithm tend to listen for a longer duration on average.")

"""1. Recaps Tests Used: It reminds the reader that Welch's t-test was chosen based on the results of the normality and Levene's tests.
2. Interprets Levene's Test: It explicitly states the conclusion from Levene's test (unequal variances).
3. Interprets Welch's t-test p-value: It clearly explains the statistically significant p-value and the rejection of the null hypothesis.
4. States the Significance: It reiterates that there is a statistically significant difference in 'Duration Played' between the groups.
5. Quantifies the Difference: It highlights the substantial difference in the mean 'Duration Played' between the Target and Control groups. It also mentions the similar trend in the median values.
6. Provides a Concluding Statement: It concludes that the new algorithm has a positive impact on listening time, suggesting an increase in user engagement in terms of duration.

The analysis of listening duration revealed a statistically significant increase among users exposed to the new playlist recommendation algorithm (Target group) compared to the control group (p < 0.05, Welch's t-test). On average, users in the Target group listened for a significantly longer duration (mean of 159.91 seconds) than those in the Control group (mean of 120.07 seconds). This indicates that the new algorithm is effective in encouraging users to engage with the platform for extended periods, suggesting a positive impact on user engagement as measured by listening time.
"""

